language: node_js
node_js:
  - 8
  - 7
  - 6
  - 4
install:
  - npm install
after_script:
  - 'cat ./coverage/lcov.info | coveralls'
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  email:
    recipients:
      - geoffrey.testelin@gmail.com
    on_success: always
    on_failure: always