language: node_js
node_js:
  - 7
  - 6
  - 4
install:
  - npm install
after_script: 'cat ./coverage/lcov.info | coveralls'
notifications:
  email:
    recipients:
      - geoffrey.testelin@gmail.com
    on_success: always
    on_failure: always