# Theme configuration
theme: jekyll-theme-cayman
title: Generator Cozen Angular
description: A simple generator to help you create AngularJS applications using the library AAL for Altran Angular projects.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/generator-cozen-angular/
baseUrl: https://c0zen.github.io/generator-cozen-angular/
gitHubUrl: https://github.com/C0ZEN/generator-cozen-angular
