# Theme configuration
theme: jekyll-theme-cayman
title: Generator Altran Angular
description: A simple generator to help you create AngularJS applications using the internal library for Altran projects.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/Generator-Altran-Angular/
